// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVszzsmym0u4ujrwU4eL0s2ZIkqNcoeQ',
    appId: '1:643270209299:android:eb759b3bf99d16a18474e6',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    storageBucket: 'faculty-lms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjPa5dlGpt6EFgeuOgRzaBSelkdEft4c',
    appId: '1:643270209299:ios:76b83c232278bb828474e6',
    messagingSenderId: '643270209299',
    projectId: 'faculty-lms',
    storageBucket: 'faculty-lms.appspot.com',
    androidClientId: '643270209299-cv40ppt70i7odfvg09et4fpk90b34ub2.apps.googleusercontent.com',
    iosClientId: '643270209299-1dkp7dt584qqr9ut0ticgdnrb3514ico.apps.googleusercontent.com',
    iosBundleId: 'com.spagreen.lms.user.app',
  );
}
